# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# neutrons from 20cm modulator
#
/gps/particle proton
/gps/pos/type Point
/gps/direction 0 0 1
/gps/pos/centre 0. 0. -5 m
/gps/ene/type User
/gps/hist/type energy
/tracking/verbose 0
/gps/hist/point	6	75647
/gps/hist/point	18	1251
/gps/hist/point	30	1288
/gps/hist/point	42	1302
/gps/hist/point	54	1304
/gps/hist/point	66	1314
/gps/hist/point	78	1307
/gps/hist/point	90	1271
/gps/hist/point	102	1129
/gps/hist/point	114	1108
/gps/hist/point	126	1016
/gps/hist/point	138	893
/gps/hist/point	150	808
/gps/hist/point	162	827
/gps/hist/point	174	729
/gps/hist/point	186	719
/gps/hist/point	198	631
/gps/hist/point	210	589
/gps/hist/point	222	492
/gps/hist/point	234	458
/gps/hist/point	246	415
/gps/hist/point	258	397
/gps/hist/point	270	329
/gps/hist/point	282	291
/gps/hist/point	294	296
/gps/hist/point	306	246
/gps/hist/point	318	255
/gps/hist/point	330	194
/gps/hist/point	342	172
/gps/hist/point	354	161
/gps/hist/point	366	161
/gps/hist/point	378	136
/gps/hist/point	390	125
/gps/hist/point	402	124
/gps/hist/point	414	106
/gps/hist/point	426	89
/gps/hist/point	438	58
/gps/hist/point	450	55
/gps/hist/point	462	72
/gps/hist/point	474	45
/gps/hist/point	486	38
/gps/hist/point	498	29
/gps/hist/point	510	32
/gps/hist/point	522	12
/gps/hist/point	534	17
/gps/hist/point	546	15
/gps/hist/point	558	7
/gps/hist/point	570	3
/gps/hist/point	582	0
/gps/hist/point	594	0
/gps/hist/point	606	0

#
/run/beamOn 1000000
