# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! RAONSCL2-NeutronVacuumVesselTest
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/scene/add/text 0 6 -40 cm 18 4 4 Fe
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/scene/add/text 6 7 10 cm 18 4 4 Shape2
#
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
# "Envelope" is transparent blue to represent water
/vis/geometry/set/colour downstreamSensorVolume 0 0 0 1 .3
/vis/geometry/set/colour vessel 0 1 0 1 .3
/vis/geometry/set/colour vesselUpstreamEndcap 0 1 0 1 .3
/vis/geometry/set/colour vesselDownstreamEndcap 0 1 0 1 .3
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush


# setup gps

/gps/particle geantino
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0. 0, -5. m
/gps/pos/radius 5 m
/gps/ene/mono 7.5 MeV
/gps/ang/type iso

# biases
/gps/hist/type biasx
/gps/hist/point -5.5 3
/gps/hist/point -4.5 6
/gps/hist/point -3.5 13
/gps/hist/point -2.5 40
/gps/hist/point -1.5 100
/gps/hist/point -0.5 124
/gps/hist/point 0.5 134
/gps/hist/point 1.5 92
/gps/hist/point 2.5 45
/gps/hist/point 3.5 11
/gps/hist/point 4.5 6
/gps/hist/point 5.5 4

/gps/hist/type biasy
/gps/hist/point -5.5 7
/gps/hist/point -4.5 11
/gps/hist/point -3.5 11
/gps/hist/point -2.5 35
/gps/hist/point -1.5 81
/gps/hist/point -0.5 119
/gps/hist/point 0.5 132
/gps/hist/point 1.5 106
/gps/hist/point 2.5 48
/gps/hist/point 3.5 18
/gps/hist/point 4.5 7
/gps/hist/point 5.5 3

/gps/hist/type theta
/gps/hist/point 0.25 1
/gps/hist/point 0.35 8
/gps/hist/point 0.45 14
/gps/hist/point 0.55 31
/gps/hist/point 0.65 31
/gps/hist/point 0.75 32
/gps/hist/point 0.85 40
/gps/hist/point 0.95 47
/gps/hist/point 1.05 87
/gps/hist/point 1.15 87
/gps/hist/point 1.25 78
/gps/hist/point 1.35 90
/gps/hist/point 1.45 31
/gps/hist/point 1.55 1
